### ISSUE TITLE
Running Unprotect in source machine errors out

### ISSUE THREAD

**Issue by TohnoCoding** [Jackabomb/dotnet-protect-cli#1]
CLI run of the Unprotect tool crashes with the following messages:

![image](https://github.com/user-attachments/assets/0e248ce7-acfa-4e92-9373-4c99c46cd5ad)

Can't run Unprotect in source machine.

Specs:
Win10 v22H2 (build 19045.5011)
Intel i5 6500 3.2GHz
32GB DDR4 RAM
DotNet 8 (Runtime, Desktop Runtime, AspNetCore, SDK)

EDIT: I checked the source and it's just a single line; couldn't it be converted to a PowerShell script? Might present less issues than trying to run this CLI tool.

**Comment by TohnoCoding** [comment]
Yep, the CLI apps can be converted to PowerShell, preventing anything like my error above.

Unprotect.ps1
```
$input = Read-Host "Enter the Base64-encoded encrypted data from the source host:"
$decryptedData = [System.Security.Cryptography.ProtectedData]::Unprotect(
    [Convert]::FromBase64String($input),
    $null,
    [System.Security.Cryptography.DataProtectionScope]::CurrentUser
)
Write-Output "`nHere's your output encoded string:`n"
Write-Output ([Convert]::ToBase64String($decryptedData))
```

Reprotect.ps1
```
$input = Read-Host "Enter the Base64-encoded encrypted data for the target host:"
$decryptedData = [System.Security.Cryptography.ProtectedData]::Unprotect(
    [Convert]::FromBase64String($input),
    $null,
    [System.Security.Cryptography.DataProtectionScope]::CurrentUser
)
Write-Output "`nHere's your output encoded string:`n"
Write-Output ([Convert]::ToBase64String($decryptedData))
```
Logic stays the same -- Unprotect runs on the source machine and Reprotect runs on the target machine. Managed to get KeeAnywhere working through this.

Thanks for the work on the original code!

**Comment by Jackabomb** [comment]
@TohnoCoding 
Cool! I'm glad you got it working. I don't know Powershell, so it never occurred to me to do it that way.

If you still feel like investigating the CLI issue, can you post the output of `dotnet --list-runtimes` ?

**Comment by TohnoCoding** [comment]
Apparently it had something to do with my virus protection and the antivirus detecting it as a potential positive. It's all good now though. I highly suggest you also take the PowerShell code and put it in the repo, I don't mind if you do, in case other people face the same issue I did.

**Comment by Jackabomb** [comment]
@TohnoCoding 
Do you want to open a PR?

**Comment by TohnoCoding** [comment]
Done.
